/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.fatec.mainframe;

import edu.fatec.mainframe.Main;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        Main classUnderTest = new Main();
        assertNotNull("app should have a greeting", classUnderTest.getClass());
    }
}
